require('user.options')
require('user.keymaps')
require('user.plugins')
require('user.colorscheme')
require('user.cmp')
require('user.snippets')
require('user.lsp')
require('user.neotree')
require('user.treesitter')
require('user.gitsigns')
require('user.aerial')

